export const COMMIT_CHART = "COMMIT_CHART"
export const EDIT_CHART = "EDIT_CHART"
export const REMOVE_PART = "REMOVE_PART"
export const SELECT_CHORD = "SELECT_CHORD"
export const SELECT_KEY = "SELECT_KEY"
